#!/bin/bash
set -eu
PYTHON="$1"
PYENV="$HOME/.pyenv"
CACHE="$HOME/.cache/pyenv"

set -x
if ! [ -d $CACHE/$PYTHON ]; then
    mkdir -p $CACHE/
    if [ -d $PYENV/versions/$PYTHON ]; then
        ln -sf  $PYENV/versions/$PYTHON $CACHE/$PYTHON
    else
        $PYENV/plugins/python-build/bin/python-build $PYTHON $CACHE/$PYTHON
    fi
fi

ln -sfn $CACHE/$PYTHON ~/python

# some of these come with ancient, broken virtualenvs installed
# we'll just use the system one
~/python/bin/pip uninstall --yes virtualenv || true
