#!/bin/bash
set -eu

### definitions
source CI/env
PATH=$PWD/CI/circle:~/python/bin:$PATH
trap timestamp EXIT

### main
set -x
: $TOX_TESTENV_PASSENV

### machine
lsb_release -a
test $CIRCLE_NODE_TOTAL -eq 4

### per-node actions
timestamp
./CI/install/main
timestamp
case $CIRCLE_NODE_INDEX in
0)
    install-python 2.7.10
    PYTHON=python2.7 runtest
    ;;
1)
    install-python 3.5.0
    PYTHON=python3.5 runtest
    ;;
2)
    install-python pypy-5.1
    PYTHON=pypy runtest
    ;;
esac
