#!/bin/bash
set -eu

fail() { echo '[31;1mFAIL[m'; }
trap fail ERR

if [ -n "$VIRTUAL_ENV" -a -d $VIRTUAL_ENV/local ]; then
    # see: https://bitbucket.org/ned/coveragepy/issue/340/keyerror-subpy
    rm -rf $VIRTUAL_ENV/local
    find $VIRTUAL_ENV -name '*.pyc' -print0 | xargs -0r rm
    find $VIRTUAL_ENV -name '__pycache__' -print0 | xargs -0r rmdir
fi

export TOP=$(dirname $(readlink -f $0))
export PROJECT=pgctl
export src=$($TOP/tests/testing/get_modulefile.py $PROJECT)

# See: http://nedbatchelder.com/code/coverage/subprocess.html
$TOP/tests/testing/install_coverage_pth.py

# careful not to leave .coverage.$HOST.$RANDOM files laying about on failure.
combine() { coverage combine --rcfile=$TOP/.coveragerc; }
trap combine ERR

combine
coverage erase --rcfile=$TOP/.coveragerc
COVERAGE_PROCESS_START=$TOP/.coveragerc py.test "$@" $TOP/tests $src
combine
coverage html --rcfile=$TOP/.coveragerc
coverage report --rcfile=$TOP/.coveragerc

pre-commit run --all-files
