#!/bin/bash
echo sweet
echo sweet_error >&2

# worst case behavior: really slow stop
slowterm() {
    echo clear trap
    trap - TERM INT
    echo sleep
    sleep 4
    echo exit
    exit -15
}
trap slowterm TERM INT

sleep infinity &
wait  # bash only handles signals when *it* is in the foreground
