#!/bin/bash -eu
echo 'hello, i am a pre-start script in stdout'
echo 'hello, i am a pre-start script in stderr' >&2
echo "--> \$PWD basename: $(basename "$PWD")" >&2
echo "--> cwd basename: $(basename "$(pwd)")" >&2
