#!/bin/bash
set -eux
# set umask to be ubuntu default
umask 022
chmod -R g-w .

pip install --upgrade pip
pip install --upgrade -r CI/install/requirements.txt

# TODO: pre-install the pre-commit hooks
