#!/bin/bash
# install s6 from github/bukzor/s6-packaging
set -eu

DISTRO="$(lsb_release -si | tr '[:upper:]' '[:lower:]')"
CODENAME="$(lsb_release -sc)"
URL="https://github.com/bukzor/s6-packaging/releases/download/v2.2.0.1-1"

s6="$DISTRO.$CODENAME.s6_2.2.0.1-1_amd64.deb"
execline="$DISTRO.$CODENAME.execline_2.1.3.1-1_amd64.deb"
skalibs="$DISTRO.$CODENAME.skalibs_2.3.6.1-1_amd64.deb"

set -x
wget -N $URL/$s6 $URL/$execline $URL/$skalibs
sudo dpkg -i $s6 $execline $skalibs
