#!/bin/bash
echo sweet
echo sweet_error >&2

# worst case behavior: really slow stop
slowterm() {
    trap - TERM INT
    sleep 0.75 &
    # during this test case, we've set the PGCTL_WAIT_PERIOD to 1.5 seconds
    sleep 2.25
}
trap slowterm TERM INT

# infinite busy loop; bash only handles signals when it is foreground
while true; do
    true
done
