#!/bin/bash
echo sweet
echo sweet_error >&2

slowterm() {
    # ignore SIGTERM for the moment
    trap '' TERM

    # worst case behavior: really slow stop
    # during this test case, we've set the PGCTL_WAIT_PERIOD to 1.5 seconds
    sleep $BACKGROUND_SLEEP &
    sleep $FOREGROUND_SLEEP

    # the usual exit code (128 + 15 means SIGTERM)
    exit 143
}
trap slowterm TERM INT

# infinite busy loop; bash only handles signals when it is foreground
while true; do
    true
done
