#!/bin/bash
set -eu
# Users must follow this pattern if they can't exec a single subprocess.
# TODO: simplify this use case by improving dumb-init:
#       https://github.com/Yelp/dumb-init/issues/4
term() {
    # ignore SIGTERM for the moment
    trap '' TERM
    # list the process leader of each job, kill them all
    jobs -p | xargs -n1 --verbose kill
    # the usual exit code (128 + 15 means SIGTERM)
    exit 143
}
trap term TERM

yes oh, hi! | pv -qL 10 &
yes error | pv -qL 10 >&2 &

wait
