#!/bin/bash
set -eu
# Users must follow this pattern if they can't exec a single subprocess.
# TODO: simplify this use case by improving dumb-init:
#       https://github.com/Yelp/dumb-init/issues/4
# FIXME: this recipe still doesn't work if there's a full pipeline buffer that
#       takes significant time to empty: yes | pv -qL 10
term() {
    # ignore SIGTERM for the moment
    trap '' TERM
    # list the process leader of each job, kill them all
    jobs -p | xargs -n1 --verbose kill
    # the usual exit code (128 + 15 means SIGTERM)
    exit 143
}
trap term TERM

slowprint() {
    while :; do
        echo "$@"
        sleep 0.1
    done
}

slowprint oh, hi! &
slowprint error >&2 &

wait
