#!/usr/bin/env python3
"""Spawn a subprocess while closing its fds.

This evades pgctl's main fuser-based process tracking, which is based on which
processes hold a file open.
"""
import subprocess


def main():
    proc = subprocess.Popen(('sleep', 'infinity'), close_fds=True)
    with open('child.pid', 'w') as f:
        f.write(str(proc.pid) + '\n')
    proc.communicate()
    return proc.returncode


if __name__ == '__main__':
    exit(main())
